on:
  schedule:
    - cron: '15 3 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for upstream changes
        id: check
        run: |
          git remote add upstream https://github.com/hjd1964/OnStepX.git
          git fetch upstream main
          git log HEAD..upstream/main --oneline > commits.txt
          if [ -s commits.txt ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No new commits."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - if: steps.check.outputs.has_changes == 'true'
        uses: tgymnich/fork-sync@v2.0
        with:
          owner: joxda
          base: main
          head: main